defaults:
  - _self_
  - model: small
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

batch_size: 4
num_warmup_steps: 5
num_measurement_steps: 10
forward_only: ??
use_optimizer: ??
mixed_precision: false
mem_profile: false

model:
  _target_: cs336_basics.model.BasicsTransformerLM
  vocab_size: 10000
  context_length: 256
  d_model: ??
  num_layers: ??
  num_heads: ??
  d_ff: ??
  rope_theta: 10000

optimizer:
  _target_: cs336_basics.optimizer.AdamW
  _convert_: all
  params: ??
  lr: 1e-3
  betas: [0.9, 0.95]
  eps: 1e-8
  weight_decay: 1e-2